# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Blank
    url: '#01-blank'
    weight: 10
  - name: Hero
    url: '#02-hero'
    weight: 20
  - name: About Me
    url: '#03-aboutme'
    weight: 30
  - name: Skills
    url: '#04-skills'
    weight: 40
  - name: Experience
    url: '#05-experience'
    weight: 50
  - name: Accomplishments
    url: '#06-accomplishments'
    weight: 60
  - name: Contentfeeds
    url: '#07-contentfeed-posts'
    weight: 70
  - name: Featured
    url: '#08-featured'
    weight: 80
  - name: Contact
    url: '#09-contact'
    weight: 90  
  - name: tags
    url: '#11-tags'
    weight: 110   
  - name: Projects
    url: '#projects'
    weight: 200
  - name: Book
    url: '/book/example/'
    weight: 300

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
